blueprints = {
    # IME0010: Álgebra Linear {{{
    "IME0010": {
        "name": "Álgebra Linear",
        "cron": [
            ("Sistemas lineares e matrizes", 18),
            ("Avaliações", 2),
            ("Espaços Vetoriais", 10),
            ("Transformações lineares", 10),
            ("Avaliações", 2),
            ("Autovalores e autovetores", 10),
            ("Espaços com produto interno", 10),
            ("Avaliações", 2),
        ],
    },
    # }}}
    # IME0379: Cálculo 1B {{{
    "IME0379": {
        "name": "Cálculo 1B",
        "cron": [
            ("Apresentação da disciplina", 2),
            ("Funções: definição e domínio", 2),
            ("Funções definidas por partes", 2),
            ("Funções polinomiais e racionais", 2),
            ("Funções trigonométricas: gráficos e propriedades", 2),
            ("Propriedades e composição de funções", 2),
            ("Funções exponencial e logarítmica: gráficos e propriedades", 2),
            ("Os problemas da tangente e da velocidade", 2),
            ("Definição de limite e limites laterais", 2),
            ("Limites infinitos", 2),
            ("Propriedades e cálculos de limites", 2),
            ("Limites no infinito", 2),
            ("Continuidade", 2),
            ("Derivada: definição, velocidade instantânea e reta tangente", 2),
            ("Derivada como função. Diferenciabilidade e continuidade", 2),
            ("Aula de exercícios", 2),
            ("Avaliação 1", 2),
            ("Derivada de funções polinomiais e exponenciais", 2),
            ("Regras do produto e do quociente", 2),
            ("Derivada de funções trigonométricas", 2),
            ("Regra da cadeia", 2),
            ("Derivada de funções logarítmicas", 2),
            ("Valores Máximo e mínimo", 2),
            ("Intervalos de crescimento e decrescimento", 2),
            ("Concavidade e pontos de inflexão", 2),
            ("Formas indeterminadas e regra de L’Hospital", 2),
            ("Esboço de curvas", 2),
            ("Esboço de curvas - Continuação", 2),
            ("Problemas de otimização", 2),
            ("Antiderivada", 2),
            ("Aula de exercícios", 2),
            ("Avaliação 2", 2),
        ],
    },
    # }}}
    # IME0388: Análise Real {{{
    "IME0388": {
        "name": "Análise Real",
        "cron": [
            ("Apresentação da disciplina", 2),
            ("Noções de Conjuntos", 2),
            ("Noções de Funções", 2),
            ("O conjunto dos números naturais e os axiomas de Peano", 2),
            ("Conjuntos finitos e suas propriedades", 2),
            ("Conjuntos finitos, infinitos e enumeráveis", 2),
            ("Conjuntos Infinitos e enumeráveis", 2),
            ("O conjunto dos números reais como corpo ordenado", 2),
            ("Supremos e ínfimos em um corpo ordenado", 2),
            ("A incompletude dos Racionais e o Postulado de Dedekind", 2),
            ("Densidade dos Racionais", 2),
            ("Não enumerabilidade do conjunto dos números reais", 2),
            ("Aula de exercícios", 2),
            ("Avaliação 1", 2),
            ("Sequência de números reais", 2),
            ("Sequencias monótonas e propriedades aritméticas de limites", 2),
            ("Sequencias especiais e o número de Euler", 2),
            ("O Teorema de Bolzano Weierstrass e lim sup e lim inf", 2),
            ("Sequencias de Cauchy e caracterização de convergência", 2),
            ("Limites infinitos", 2),
            ("Séries Numéricas", 2),
            ("Teste da comparação, serie p e Teorema de Leibniz para", 2),
            ("Séries alternadas", 2),
            ("Séries absolutamente convergentes e testes de convergência", 2),
            ("Pontos interiores e conjuntos abertos", 2),
            ("Conjuntos fechados e pontos de acumulação", 2),
            ("Conjuntos compactos", 2),
            ("O Conjunto de Cantor", 2),
            ("Aula de exercícios", 2),
            ("Avaliação 2", 2),
            ("Limites de funções", 2),
            ("Limites de funções", 2),
            ("Limites Laterais", 2),
            ("Propriedades de limites e limites da composta", 2),
            ("Limites Laterais", 2),
            ("Limites Laterais em funções monótonas e Limites Infinitos", 2),
            ("Limites no infinito", 2),
            ("Funções Contínuas", 2),
            ("Funções Contínuas", 2),
            ("Um pouco mais sobre descontinuidades", 2),
            ("Funções contínuas em intervalos", 2),
            ("Funções contínuas em compactos e o Teorema de Weiestrass", 2),
            ("Continuidade Uniforme", 2),
            ("Teorema da extensão contínua", 2),
            ("Aula de exercícios", 2),
            ("Avaliação 3", 2),
            ("Entrega de resultados", 2),
        ],
    },
    # }}}
    # IME0415: Espaços Métricos {{{
    "IME0415": {
        "name": "Espaços Métricos",
        "cron": [
            ("Espaços métricos: Definição e exemplos", 2),
            ("Espaços métricos: Bolas e esferas", 2),
            ("Espaços métricos: Conjuntos limitados", 2),
            ("Espaços métricos: Distânica entre conjuntos", 2),
            ("Espaços métricos: Isometrias", 2),
            ("Funções Contínuas: Definição e exemplos", 2),
            ("Funções Contínuas: Propriedades elementares", 2),
            ("Funções Contínuas: Homeomorfismos", 2),
            ("Funções Contínuas: Métricas equivalentes", 2),
            ("Funções Contínuas: Transformações multilineares", 2),
            ("Topologia: Conjuntos abertos", 2),
            ("Topologia: Conjuntos abertos e continuidade", 2),
            ("Topologia: Espaços topológicos", 2),
            ("Topologia: Conjuntos fechados", 2),
            ("Avaliação 1", 2),
            ("Conjuntos conexos: Definição e exemplos", 2),
            ("Conjuntos conexos: Propriedades dos conjuntos conexos", 2),
            ("Conjuntos conexos: Conexidade por caminhos", 2),
            ("Conjuntos conexos: Componentes conexas", 2),
            ("Conjuntos conexos: A conexidade como invariante topológico", 2),
            ("Limites: Limites de sequências", 2),
            ("Limites: Sequências de números reais", 2),
            ("Limites: Séries", 2),
            ("Limites: Convergência e topologia", 2),
            ("Limites: Sequências de funções", 2),
            ("Limites: Produtos cartesianos infinitos", 2),
            ("Limites: Limites de funções", 2),
            ("Continuidade uniforme", 2),
            ("Avaliação 2", 2),
            ("Espaços completos: Sequências de Cauchy", 2),
            ("Espaços completos: Espaços métricos completos", 2),
            ("Espaços completos: Espaços de Banach e espaços de Hilbert", 2),
            ("Espaços completos: Extensão de aplicações contínuas", 2),
            ("Espaços completos: O Teorema de Baire", 2),
            ("Espaços completos: O método das aproximações sucessivas", 2),
            ("Espaços compactos: Compacidade na reta", 2),
            ("Espaços compactos: Espaços métricos compactos", 2),
            ("Espaços compactos: Produto Cartesiano por um fator Compacto", 2),
            ("Espaços compactos: Uma base para C(K,M)", 2),
            ("Espaços compactos: Caracterizações de espaços compactos", 2),
            ("Espaços compactos: Produtos cartesianos de espaços compactos", 2),
            ("Espaços compactos: Continuidade uniforme", 2),
            ("Espaços compactos: Espaços localmente compactos", 2),
            ("Espaços compactos: Espaços vetoriais normados de dimensão finita", 2),
            ("Espaços compactos: Equicontinuidade", 2),
            ("Espaços compactos: O Teorema de Stone-Weierstrass", 2),
            ("Avaliação 3", 2),
        ],
    },
    # }}}
    # IME0416: Teoria de Galois {{{
    "IME0416": {
        "name": "Teoria de Galois",
        "cron": [
            ("Corpos e Corpo de decomposição de um polinômio", 4),
            ("Revisão de extensões de corpos", 2),
            ("Extensões normais e separáveis", 4),
            ("Grupos de Galois e extensões galoisianas", 6),
            ("Teorema Fundamental da Teoria de Galois", 14),
            ("Revisão de grupos solúveis e solubilidade por radicais", 6),
            ("Avaliação", 2),
            ("Corpos finitos", 8),
            ("Extensões ciclotômicas", 6),
            ("Construções por régua e compasso", 2),
            ("Teorema Fundamental da Álgebra", 2),
            ("Norma e traço", 2),
            ("Apresentação de exercícios", 4),
            ("Avaliação", 2),
        ],
    },
    # }}}
    # IME0411: Álgebra Linear II {{{
    "IME0411": {
        "name": "Álgebra Linear II",
        "cron": [
            ("Transformações Lineares", 10),
            ("Subespaços invariantes", 10),
            ("O teorema da decomposição primária", 6),
            ("Decomposições cíclicas, Forma Racional e Forma Canônica de Jordan", 10),
            ("Espaços com produto interno", 6),
            ("Operadores unitários e Operadores Normais", 6),
            ("Teorema Espectral", 4),
            ("Formas bilineares", 6),
            ("Avaliações", 6),
        ],
    },
    # }}}
}
